## Recommendation System

<img src="https://miro.medium.com/max/1064/1*mz9tzP1LjPBhmiWXeHyQkQ.png"/>

### Content-Based Filtering

Rekomendasi diberikan berdasarkan features dari item yang disukai user


In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
produk = ["Gundam Doraemon Tsubasa", "Gundam Gundam Gundam"]

In [3]:
extractor = CountVectorizer()

In [4]:
exfit = extractor.fit_transform(produk)

In [5]:
extractor.get_feature_names()

['doraemon', 'gundam', 'tsubasa']

In [6]:
extractor.fit_transform(produk).toarray()

array([[1, 1, 1],
       [0, 3, 0]], dtype=int64)

In [7]:
exfit.toarray()

array([[1, 1, 1],
       [0, 3, 0]], dtype=int64)

### Cosinus Similarity

In [10]:
score = cosine_similarity(exfit)
score
        #    x[0]            x[1]
#x[0]     # ([[1.        , 0.57735027],
#x[1]     # [0.57735027, 1.        ]])

array([[1.        , 0.57735027],
       [0.57735027, 1.        ]])

In [11]:
df = pd.DataFrame([
    {'title': 'BengawanSolo', 'genre': 'Keroncong', 'label': 'A'},
    {'title': 'Gula-Gula', 'genre': 'Dangdut', 'label': 'A'},
    {'title': 'Pelangi', 'genre': 'Pop', 'label': 'A'},
    {'title': 'Hujan', 'genre': 'Pop', 'label': 'B'},
    {'title': 'Meratapi', 'genre': 'Dangdut', 'label': 'B'},
    {'title': 'Riwayat', 'genre': 'Keroncong', 'label': 'B'},
    {'title': 'CintaHidup', 'genre': 'Pop', 'label': 'C'},
    {'title': 'Malang', 'genre': 'Keroncong', 'label': 'C'},
    {'title': 'TresnoAti', 'genre': 'Dangdut', 'label': 'C'}
    ])
df

title      genre label
0  BengawanSolo  Keroncong     A
1     Gula-Gula    Dangdut     A
2       Pelangi        Pop     A
3         Hujan        Pop     B
4      Meratapi    Dangdut     B
5       Riwayat  Keroncong     B
6    CintaHidup        Pop     C
7        Malang  Keroncong     C
8     TresnoAti    Dangdut     C

In [12]:
ecv = CountVectorizer()
matrix_genre = ecv.fit_transform(df['genre'])
matrix_genre

<9x3 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [13]:
ecv.get_feature_names()

['dangdut', 'keroncong', 'pop']

In [14]:
matrix_genre.toarray()

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]], dtype=int64)

In [15]:
csScore = cosine_similarity(matrix_genre)
csScore

array([[1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1.]])

In [16]:
#User suka dengan index ke-0
# productSimilar = csScore[0]

Mirip = list(enumerate(csScore[0]))
Mirip = sorted(Mirip, key=lambda x:x[1], reverse=True)
print(Mirip) 

[(0, 1.0), (5, 1.0), (7, 1.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (6, 0.0), (8, 0.0)]


In [17]:
for i in Mirip[:5]:
    print(df.iloc[i[0]])

title    BengawanSolo
genre       Keroncong
label               A
Name: 0, dtype: object
title      Riwayat
genre    Keroncong
label            B
Name: 5, dtype: object
title       Malang
genre    Keroncong
label            C
Name: 7, dtype: object
title    Gula-Gula
genre      Dangdut
label            A
Name: 1, dtype: object
title    Pelangi
genre        Pop
label          A
Name: 2, dtype: object
